//! Verified ingestion and exact lookup for normalized Blizzard generated-API drafts.
//!
//! The source revision is evidence attached to one completed draft. It is not a
//! permanent upstream pin: callers resolve a moving source selector again for
//! every new operation and then pass the resulting exact draft here.

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fmt;

use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};
use wow_core::canonical_json_bytes;

/// Current normalized draft schema understood by this adapter.
pub const BLIZZARD_API_DRAFT_SCHEMA: &str = "wow.reference-draft.blizzard-generated-api/v1";

/// Failure while decoding or verifying a generated-API draft.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlizzardApiDraftError {
    /// The JSON representation could not be decoded.
    Json(String),
    /// Canonical JSON could not be produced.
    Canonical(String),
    /// One schema invariant was violated.
    Invalid(String),
}

impl fmt::Display for BlizzardApiDraftError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Json(message) => write!(formatter, "invalid Blizzard API draft JSON: {message}"),
            Self::Canonical(message) => {
                write!(formatter, "cannot canonicalize Blizzard API draft: {message}")
            }
            Self::Invalid(message) => write!(formatter, "invalid Blizzard API draft: {message}"),
        }
    }
}

impl Error for BlizzardApiDraftError {}

fn invalid(message: impl Into<String>) -> BlizzardApiDraftError {
    BlizzardApiDraftError::Invalid(message.into())
}

fn is_sha256(value: &str) -> bool {
    value.len() == 71
        && value.starts_with("sha256:")
        && value[7..]
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn is_git_object_id(value: &str) -> bool {
    (40..=64).contains(&value.len())
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn bytes_to_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut result = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        result.push(char::from(HEX[usize::from(byte >> 4)]));
        result.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    result
}

fn raw_draft_digest(root: &Value) -> Result<String, BlizzardApiDraftError> {
    let mut projection = root.clone();
    let object = projection
        .as_object_mut()
        .ok_or_else(|| invalid("root must be a JSON object"))?;
    object.remove("draft_digest");
    let canonical = canonical_json_bytes(&projection)
        .map_err(|error| BlizzardApiDraftError::Canonical(error.to_string()))?;
    let digest = Sha256::digest(canonical);
    Ok(format!("sha256:{}", bytes_to_hex(&digest)))
}

/// Producer identity and configuration included in draft identity.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiProducer {
    /// Stable producer identifier.
    pub id: String,
    /// Producer implementation version.
    pub version: String,
    /// Configuration that affects generated bytes.
    #[serde(default)]
    pub configuration: BTreeMap<String, Value>,
    /// Forward-compatible producer metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// Exact source identity used by one draft generation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiSourceIdentity {
    /// Digest of the verified source manifest.
    pub manifest_digest: String,
    /// Generic source identifier.
    pub source_id: String,
    /// Moving selector resolved at operation start, when recorded.
    pub selector: Option<String>,
    /// Exact Git object identifier used throughout the operation.
    pub revision: String,
    /// Version reported by that exact source revision, when available.
    pub version: Option<String>,
    /// Forward-compatible source metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// Coverage state for one generated documentation file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum BlizzardApiFileStatus {
    /// The file was parsed and normalized.
    Parsed,
    /// The file could not be parsed or verified.
    Failed,
}

/// Per-file coverage entry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiFileCoverage {
    /// Canonical source path.
    pub path: String,
    /// Producer result for this file.
    pub status: BlizzardApiFileStatus,
    /// Forward-compatible coverage metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// Explicit failed-file record retained by diagnostic partial drafts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiFileFailure {
    /// Canonical source path.
    pub path: String,
    /// Bounded producer failure description.
    pub error: String,
    /// Forward-compatible failure metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// Aggregate normalized-record counts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlizzardApiRecordCounts {
    /// System records.
    pub systems: u64,
    /// Function records.
    pub functions: u64,
    /// Event records.
    pub events: u64,
    /// Structure/enumeration/table records.
    pub tables: u64,
    /// Fields across table records.
    pub fields: u64,
}

/// Completeness of the generated documentation universe.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum BlizzardApiCoverageStatus {
    /// Every candidate generated document was verified and parsed.
    Complete,
    /// At least one candidate document failed.
    Partial,
}

/// Coverage and negative-authority state for the draft.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiCoverage {
    /// Aggregate completeness state.
    pub status: BlizzardApiCoverageStatus,
    /// Number of generated documentation candidates.
    pub candidate_files: u64,
    /// Number of successfully parsed candidates.
    pub parsed_files: u64,
    /// Explicit failures.
    #[serde(default)]
    pub failed_files: Vec<BlizzardApiFileFailure>,
    /// Status of every candidate file.
    pub files: Vec<BlizzardApiFileCoverage>,
    /// Aggregate normalized-record counts.
    pub record_counts: BlizzardApiRecordCounts,
    /// Whether exact lookup misses may prove absence in this universe.
    pub negative_authority: bool,
    /// Forward-compatible coverage metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// Exact source pointer retained on normalized records.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiSourcePointer {
    /// Canonical generated-document path.
    pub path: String,
    /// SHA-256 of the exact source bytes.
    pub sha256: String,
    /// Local variable passed to `AddDocumentationTable`.
    pub document_variable: String,
    /// Forward-compatible source metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// One normalized argument, return value, payload item, or table field.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiParameter {
    /// One-based declaration position.
    pub position: u64,
    /// Declared name.
    pub name: String,
    /// Declared generated type.
    #[serde(rename = "type")]
    pub value_type: String,
    /// Whether the generated documentation marks the value nilable.
    pub nilable: bool,
    /// Generated prose attached to the declaration.
    #[serde(default)]
    pub documentation: Vec<String>,
    /// Generated default value, when present.
    #[serde(default)]
    pub default: Option<Value>,
    /// Generated fields not yet promoted to typed adapter fields.
    #[serde(default)]
    pub attributes: BTreeMap<String, Value>,
    /// Forward-compatible normalized metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// One normalized generated function or event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiCallable {
    /// `function` or `event`.
    pub kind: String,
    /// Unqualified generated name.
    pub name: String,
    /// Exact lookup identity.
    pub qualified_name: String,
    /// Generated prose.
    #[serde(default)]
    pub documentation: Vec<String>,
    /// Exact source pointer.
    pub source: BlizzardApiSourcePointer,
    /// Literal event token, when declared.
    #[serde(default)]
    pub event: Option<String>,
    /// Function arguments.
    #[serde(default)]
    pub arguments: Vec<BlizzardApiParameter>,
    /// Function returns.
    #[serde(default)]
    pub returns: Vec<BlizzardApiParameter>,
    /// Event payload.
    #[serde(default)]
    pub payload: Vec<BlizzardApiParameter>,
    /// Generated restriction and secrecy metadata.
    #[serde(default)]
    pub restrictions: BTreeMap<String, Value>,
    /// Other generated attributes.
    #[serde(default)]
    pub attributes: BTreeMap<String, Value>,
    /// Forward-compatible normalized metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// One normalized generated structure, enumeration, callback type, or table.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiTable {
    /// Lowercase generated table kind.
    pub kind: String,
    /// Declared name.
    pub name: String,
    /// Generated prose.
    #[serde(default)]
    pub documentation: Vec<String>,
    /// Exact source pointer.
    pub source: BlizzardApiSourcePointer,
    /// Ordered declared fields.
    #[serde(default)]
    pub fields: Vec<BlizzardApiParameter>,
    /// Other generated attributes.
    #[serde(default)]
    pub attributes: BTreeMap<String, Value>,
    /// Forward-compatible normalized metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// One generated API documentation system.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiSystem {
    /// Generated system name.
    pub name: String,
    /// Namespace used to qualify callable identities, when present.
    pub namespace: Option<String>,
    /// Generated environment marker, when present.
    pub environment: Option<String>,
    /// Generated prose.
    #[serde(default)]
    pub documentation: Vec<String>,
    /// Exact source pointer.
    pub source: BlizzardApiSourcePointer,
    /// Functions in canonical order.
    #[serde(default)]
    pub functions: Vec<BlizzardApiCallable>,
    /// Events in canonical order.
    #[serde(default)]
    pub events: Vec<BlizzardApiCallable>,
    /// Tables in canonical order.
    #[serde(default)]
    pub tables: Vec<BlizzardApiTable>,
    /// Other generated attributes.
    #[serde(default)]
    pub attributes: BTreeMap<String, Value>,
    /// Forward-compatible normalized metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// Verified normalized draft emitted from one exact source revision.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlizzardApiReferenceDraft {
    /// Draft schema identifier.
    pub schema: String,
    /// Producer identity and configuration.
    pub producer: BlizzardApiProducer,
    /// Exact source identity.
    pub source: BlizzardApiSourceIdentity,
    /// Completeness and negative-authority state.
    pub coverage: BlizzardApiCoverage,
    /// Canonically ordered normalized systems.
    pub systems: Vec<BlizzardApiSystem>,
    /// Digest over the raw canonical draft without this field.
    pub draft_digest: String,
    /// Forward-compatible top-level metadata.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

impl BlizzardApiReferenceDraft {
    /// Decodes and verifies a draft without executing source code.
    pub fn from_json(bytes: &[u8]) -> Result<Self, BlizzardApiDraftError> {
        let raw: Value = serde_json::from_slice(bytes)
            .map_err(|error| BlizzardApiDraftError::Json(error.to_string()))?;
        let supplied = raw
            .get("draft_digest")
            .and_then(Value::as_str)
            .ok_or_else(|| invalid("draft_digest is missing"))?;
        if !is_sha256(supplied) {
            return Err(invalid("draft_digest is not canonical SHA-256"));
        }
        let expected = raw_draft_digest(&raw)?;
        if supplied != expected {
            return Err(invalid("draft_digest does not match canonical content"));
        }
        let draft: Self = serde_json::from_value(raw)
            .map_err(|error| BlizzardApiDraftError::Json(error.to_string()))?;
        draft.validate()?;
        Ok(draft)
    }

    /// Verifies schema, ordering, counts, coverage and source identities.
    pub fn validate(&self) -> Result<(), BlizzardApiDraftError> {
        if self.schema != BLIZZARD_API_DRAFT_SCHEMA {
            return Err(invalid("unsupported schema"));
        }
        if self.producer.id.is_empty() || self.producer.version.is_empty() {
            return Err(invalid("producer identity is incomplete"));
        }
        if !is_sha256(&self.source.manifest_digest) {
            return Err(invalid("source manifest digest is invalid"));
        }
        if self.source.source_id.is_empty() || !is_git_object_id(&self.source.revision) {
            return Err(invalid("source identity is incomplete"));
        }
        if self.coverage.candidate_files == 0
            || self.coverage.parsed_files > self.coverage.candidate_files
        {
            return Err(invalid("coverage file counts are invalid"));
        }
        let failure_count = u64::try_from(self.coverage.failed_files.len())
            .map_err(|_| invalid("failed-file count overflows u64"))?;
        if self.coverage.parsed_files + failure_count != self.coverage.candidate_files {
            return Err(invalid("parsed and failed files do not cover all candidates"));
        }
        let coverage_file_count = u64::try_from(self.coverage.files.len())
            .map_err(|_| invalid("coverage-file count overflows u64"))?;
        if coverage_file_count != self.coverage.candidate_files {
            return Err(invalid("coverage file array does not match candidate count"));
        }
        let complete = self.coverage.status == BlizzardApiCoverageStatus::Complete;
        if complete != self.coverage.failed_files.is_empty()
            || self.coverage.negative_authority != complete
        {
            return Err(invalid(
                "coverage status, failures and negative authority disagree",
            ));
        }

        let mut previous_path: Option<&str> = None;
        let mut parsed_paths = BTreeSet::new();
        let mut failed_paths = BTreeSet::new();
        for file in &self.coverage.files {
            if file.path.is_empty() {
                return Err(invalid("coverage contains an empty path"));
            }
            if previous_path.is_some_and(|previous| previous.as_bytes() >= file.path.as_bytes()) {
                return Err(invalid("coverage paths are not unique bytewise-sorted values"));
            }
            previous_path = Some(&file.path);
            match file.status {
                BlizzardApiFileStatus::Parsed => {
                    parsed_paths.insert(file.path.as_str());
                }
                BlizzardApiFileStatus::Failed => {
                    failed_paths.insert(file.path.as_str());
                }
            }
        }
        let declared_failed: BTreeSet<&str> = self
            .coverage
            .failed_files
            .iter()
            .map(|failure| failure.path.as_str())
            .collect();
        if failed_paths != declared_failed {
            return Err(invalid("failed-file records do not match file coverage"));
        }

        let mut counts = BlizzardApiRecordCounts {
            systems: 0,
            functions: 0,
            events: 0,
            tables: 0,
            fields: 0,
        };
        let mut previous_system: Option<(&str, &str)> = None;
        let mut function_names = BTreeSet::new();
        let mut event_names = BTreeSet::new();
        let mut table_names = BTreeSet::new();
        for system in &self.systems {
            if system.name.is_empty() {
                return Err(invalid("system name is empty"));
            }
            let system_key = (system.namespace.as_deref().unwrap_or(""), system.name.as_str());
            if previous_system.is_some_and(|previous| previous >= system_key) {
                return Err(invalid("systems are not unique and canonically sorted"));
            }
            previous_system = Some(system_key);
            validate_source_pointer(&system.source, &parsed_paths)?;
            counts.systems = counts
                .systems
                .checked_add(1)
                .ok_or_else(|| invalid("system count overflow"))?;
            validate_callables(
                &system.functions,
                "function",
                system.namespace.as_deref(),
                &parsed_paths,
                &mut function_names,
            )?;
            validate_callables(
                &system.events,
                "event",
                system.namespace.as_deref(),
                &parsed_paths,
                &mut event_names,
            )?;
            counts.functions = counts
                .functions
                .checked_add(u64::try_from(system.functions.len()).map_err(|_| invalid("function count overflow"))?)
                .ok_or_else(|| invalid("function count overflow"))?;
            counts.events = counts
                .events
                .checked_add(u64::try_from(system.events.len()).map_err(|_| invalid("event count overflow"))?)
                .ok_or_else(|| invalid("event count overflow"))?;
            let mut previous_table: Option<&str> = None;
            for table in &system.tables {
                if table.name.is_empty() || table.kind.is_empty() {
                    return Err(invalid("table identity is incomplete"));
                }
                if previous_table.is_some_and(|previous| previous >= table.name.as_str()) {
                    return Err(invalid("tables are not unique and canonically sorted"));
                }
                previous_table = Some(&table.name);
                validate_source_pointer(&table.source, &parsed_paths)?;
                validate_parameters(&table.fields)?;
                let identity = qualified_name(system.namespace.as_deref(), &table.name);
                if !table_names.insert(identity) {
                    return Err(invalid("duplicate table identity"));
                }
                counts.tables = counts
                    .tables
                    .checked_add(1)
                    .ok_or_else(|| invalid("table count overflow"))?;
                counts.fields = counts
                    .fields
                    .checked_add(u64::try_from(table.fields.len()).map_err(|_| invalid("field count overflow"))?)
                    .ok_or_else(|| invalid("field count overflow"))?;
            }
        }
        if counts != self.coverage.record_counts {
            return Err(invalid("record counts do not match normalized records"));
        }
        Ok(())
    }

    /// Whether exact misses may prove absence inside this generated-doc universe.
    #[must_use]
    pub fn has_negative_authority(&self) -> bool {
        self.coverage.status == BlizzardApiCoverageStatus::Complete
            && self.coverage.negative_authority
    }
}

fn qualified_name(namespace: Option<&str>, name: &str) -> String {
    namespace.map_or_else(|| name.to_owned(), |namespace| format!("{namespace}.{name}"))
}

fn validate_source_pointer(
    source: &BlizzardApiSourcePointer,
    parsed_paths: &BTreeSet<&str>,
) -> Result<(), BlizzardApiDraftError> {
    if source.path.is_empty()
        || !parsed_paths.contains(source.path.as_str())
        || !is_sha256(&source.sha256)
        || source.document_variable.is_empty()
    {
        return Err(invalid("normalized record has an invalid source pointer"));
    }
    Ok(())
}

fn validate_parameters(parameters: &[BlizzardApiParameter]) -> Result<(), BlizzardApiDraftError> {
    for (index, parameter) in parameters.iter().enumerate() {
        let expected = u64::try_from(index + 1).map_err(|_| invalid("parameter index overflow"))?;
        if parameter.position != expected || parameter.name.is_empty() || parameter.value_type.is_empty() {
            return Err(invalid("parameter identity or ordering is invalid"));
        }
    }
    Ok(())
}

fn validate_callables(
    callables: &[BlizzardApiCallable],
    expected_kind: &str,
    namespace: Option<&str>,
    parsed_paths: &BTreeSet<&str>,
    identities: &mut BTreeSet<String>,
) -> Result<(), BlizzardApiDraftError> {
    let mut previous: Option<(&str, &str)> = None;
    for callable in callables {
        if callable.kind != expected_kind || callable.name.is_empty() {
            return Err(invalid("callable identity is incomplete"));
        }
        let expected_qualified = qualified_name(namespace, &callable.name);
        if callable.qualified_name != expected_qualified {
            return Err(invalid("callable qualified name does not match its system"));
        }
        let key = (callable.qualified_name.as_str(), callable.name.as_str());
        if previous.is_some_and(|previous_key| previous_key >= key) {
            return Err(invalid("callables are not unique and canonically sorted"));
        }
        previous = Some(key);
        if !identities.insert(callable.qualified_name.clone()) {
            return Err(invalid("duplicate callable identity"));
        }
        validate_source_pointer(&callable.source, parsed_paths)?;
        validate_parameters(&callable.arguments)?;
        validate_parameters(&callable.returns)?;
        validate_parameters(&callable.payload)?;
    }
    Ok(())
}

/// Result of an exact lookup with explicit negative-authority semantics.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BlizzardApiLookup<'a, T> {
    /// One exact record was found.
    Found(&'a T),
    /// Complete coverage proves the identity absent in this universe.
    AuthoritativeAbsence,
    /// Coverage cannot prove absence.
    NotAuthoritativeAbsence,
}

/// Verified exact indexes over one immutable draft generation.
#[derive(Debug, Clone)]
pub struct BlizzardApiIndex {
    draft: BlizzardApiReferenceDraft,
    functions: BTreeMap<String, (usize, usize)>,
    events: BTreeMap<String, (usize, usize)>,
    tables: BTreeMap<String, (usize, usize)>,
    event_literals: BTreeMap<String, Vec<(usize, usize)>>,
}

impl BlizzardApiIndex {
    /// Decodes, verifies and indexes one normalized draft.
    pub fn from_json(bytes: &[u8]) -> Result<Self, BlizzardApiDraftError> {
        let draft = BlizzardApiReferenceDraft::from_json(bytes)?;
        Self::from_draft(draft)
    }

    /// Builds indexes after revalidating a typed draft.
    pub fn from_draft(draft: BlizzardApiReferenceDraft) -> Result<Self, BlizzardApiDraftError> {
        draft.validate()?;
        let mut functions = BTreeMap::new();
        let mut events = BTreeMap::new();
        let mut tables = BTreeMap::new();
        let mut event_literals: BTreeMap<String, Vec<(usize, usize)>> = BTreeMap::new();
        for (system_index, system) in draft.systems.iter().enumerate() {
            for (record_index, function) in system.functions.iter().enumerate() {
                functions.insert(function.qualified_name.clone(), (system_index, record_index));
            }
            for (record_index, event) in system.events.iter().enumerate() {
                events.insert(event.qualified_name.clone(), (system_index, record_index));
                if let Some(literal) = &event.event {
                    event_literals
                        .entry(literal.clone())
                        .or_default()
                        .push((system_index, record_index));
                }
            }
            for (record_index, table) in system.tables.iter().enumerate() {
                tables.insert(
                    qualified_name(system.namespace.as_deref(), &table.name),
                    (system_index, record_index),
                );
            }
        }
        Ok(Self {
            draft,
            functions,
            events,
            tables,
            event_literals,
        })
    }

    /// Underlying verified immutable draft.
    #[must_use]
    pub fn draft(&self) -> &BlizzardApiReferenceDraft {
        &self.draft
    }

    /// Exact function lookup by generated qualified name.
    #[must_use]
    pub fn function(&self, qualified_name: &str) -> BlizzardApiLookup<'_, BlizzardApiCallable> {
        self.functions.get(qualified_name).map_or_else(
            || self.absence(),
            |(system, record)| BlizzardApiLookup::Found(&self.draft.systems[*system].functions[*record]),
        )
    }

    /// Exact event lookup by generated qualified name.
    #[must_use]
    pub fn event(&self, qualified_name: &str) -> BlizzardApiLookup<'_, BlizzardApiCallable> {
        self.events.get(qualified_name).map_or_else(
            || self.absence(),
            |(system, record)| BlizzardApiLookup::Found(&self.draft.systems[*system].events[*record]),
        )
    }

    /// Exact table lookup by namespace-qualified generated name.
    #[must_use]
    pub fn table(&self, qualified_name: &str) -> BlizzardApiLookup<'_, BlizzardApiTable> {
        self.tables.get(qualified_name).map_or_else(
            || self.absence(),
            |(system, record)| BlizzardApiLookup::Found(&self.draft.systems[*system].tables[*record]),
        )
    }

    /// All events declaring one exact literal token.
    #[must_use]
    pub fn events_by_literal(&self, literal: &str) -> Vec<&BlizzardApiCallable> {
        self.event_literals.get(literal).map_or_else(Vec::new, |records| {
            records
                .iter()
                .map(|(system, record)| &self.draft.systems[*system].events[*record])
                .collect()
        })
    }

    fn absence<T>(&self) -> BlizzardApiLookup<'_, T> {
        if self.draft.has_negative_authority() {
            BlizzardApiLookup::AuthoritativeAbsence
        } else {
            BlizzardApiLookup::NotAuthoritativeAbsence
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn fixture(complete: bool) -> Result<Vec<u8>, Box<dyn Error>> {
        let source_pointer = json!({
            "path": "Interface/AddOns/Blizzard_APIDocumentationGenerated/ExampleDocumentation.lua",
            "sha256": format!("sha256:{}", "1".repeat(64)),
            "document_variable": "Example"
        });
        let failed_files = if complete {
            json!([])
        } else {
            json!([{"path": "failed.lua", "error": "unsupported syntax"}])
        };
        let files = if complete {
            json!([{"path": "Interface/AddOns/Blizzard_APIDocumentationGenerated/ExampleDocumentation.lua", "status": "parsed"}])
        } else {
            json!([
                {"path": "Interface/AddOns/Blizzard_APIDocumentationGenerated/ExampleDocumentation.lua", "status": "parsed"},
                {"path": "failed.lua", "status": "failed"}
            ])
        };
        let mut root = json!({
            "schema": BLIZZARD_API_DRAFT_SCHEMA,
            "producer": {"id": "test", "version": "1", "configuration": {}},
            "source": {
                "manifest_digest": format!("sha256:{}", "2".repeat(64)),
                "source_id": "fixture",
                "selector": "live",
                "revision": "3".repeat(40),
                "version": "99.0.0.1"
            },
            "coverage": {
                "status": if complete { "complete" } else { "partial" },
                "candidate_files": if complete { 1 } else { 2 },
                "parsed_files": 1,
                "failed_files": failed_files,
                "files": files,
                "record_counts": {"systems": 1, "functions": 1, "events": 1, "tables": 1, "fields": 1},
                "negative_authority": complete
            },
            "systems": [{
                "name": "Example",
                "namespace": "C_Example",
                "environment": "All",
                "documentation": [],
                "source": source_pointer,
                "functions": [{
                    "kind": "function",
                    "name": "Lookup",
                    "qualified_name": "C_Example.Lookup",
                    "documentation": [],
                    "source": source_pointer,
                    "arguments": [{"position": 1, "name": "id", "type": "number", "nilable": false, "documentation": []}],
                    "returns": [],
                    "payload": [],
                    "restrictions": {},
                    "attributes": {}
                }],
                "events": [{
                    "kind": "event",
                    "name": "Changed",
                    "qualified_name": "C_Example.Changed",
                    "event": "EXAMPLE_CHANGED",
                    "documentation": [],
                    "source": source_pointer,
                    "arguments": [],
                    "returns": [],
                    "payload": [],
                    "restrictions": {},
                    "attributes": {}
                }],
                "tables": [{
                    "kind": "structure",
                    "name": "Info",
                    "documentation": [],
                    "source": source_pointer,
                    "fields": [{"position": 1, "name": "name", "type": "cstring", "nilable": false, "documentation": []}],
                    "attributes": {}
                }],
                "attributes": {}
            }]
        });
        let digest = raw_draft_digest(&root)?;
        root.as_object_mut()
            .ok_or_else(|| invalid("fixture root must be an object"))?
            .insert("draft_digest".to_owned(), Value::String(digest));
        Ok(serde_json::to_vec(&root)?)
    }

    #[test]
    fn complete_draft_supports_authoritative_exact_lookup() -> Result<(), Box<dyn Error>> {
        let index = BlizzardApiIndex::from_json(&fixture(true)?)?;
        match index.function("C_Example.Lookup") {
            BlizzardApiLookup::Found(record) => assert_eq!(record.name, "Lookup"),
            other => return Err(format!("unexpected lookup outcome: {other:?}").into()),
        }
        assert_eq!(
            index.function("C_Example.Missing"),
            BlizzardApiLookup::AuthoritativeAbsence
        );
        assert_eq!(index.events_by_literal("EXAMPLE_CHANGED").len(), 1);
        Ok(())
    }

    #[test]
    fn partial_draft_cannot_prove_absence() -> Result<(), Box<dyn Error>> {
        let index = BlizzardApiIndex::from_json(&fixture(false)?)?;
        assert_eq!(
            index.table("C_Example.Missing"),
            BlizzardApiLookup::NotAuthoritativeAbsence
        );
        Ok(())
    }

    #[test]
    fn tampering_is_rejected() -> Result<(), Box<dyn Error>> {
        let mut root: Value = serde_json::from_slice(&fixture(true)?)?;
        root["source"]["version"] = Value::String("tampered".to_owned());
        let encoded = serde_json::to_vec(&root)?;
        assert!(BlizzardApiReferenceDraft::from_json(&encoded).is_err());
        Ok(())
    }
}
