//! Editor coordinates over the exact generated bytes, not normalized text.
use super::{LookupError, SourceLookup, check_cancelled, source_in_file, viewed_file};
use crate::native::NativeLibrary;
use serde::Serialize;
use std::sync::atomic::AtomicBool;

/// The caller selects its negotiated encoding; no editor default is inferred.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub enum PositionEncoding {
    #[serde(rename = "utf-8")]
    Utf8,
    #[serde(rename = "utf-16")]
    Utf16,
    #[serde(rename = "utf-32")]
    Utf32,
}

/// Zero-based line and encoded character offset. Columns are code units, not
/// graphemes, display cells or bytes unless Utf8 was explicitly selected.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub struct TextPosition {
    pub line: u32,
    pub character: u32,
}

/// Navigate from editor coordinates without weakening the byte-based query.
///
/// The viewed-file digest is verified before interpreting the position. LF,
/// CRLF and bare CR delimit lines; CRLF is one delimiter and no bytes are
/// rewritten. Line endings do not contribute to the character offset.
/// Out-of-line columns and positions inside a UTF-8 character or UTF-16
/// surrogate pair reject rather than clamp. End-of-line and EOF are valid
/// boundaries; their mapping behavior is identical to `source_at`.
/// Returned generated/source ranges remain half-open UTF-8 byte ranges.
/// This is an in-memory adapter, not an LSP transport or editor installation.
pub fn source_at_position<'a>(
    library: &'a NativeLibrary<'_>,
    generated_path: &str,
    expected_sha256: &str,
    position: TextPosition,
    encoding: PositionEncoding,
    cancelled: &AtomicBool,
) -> Result<SourceLookup<'a>, LookupError> {
    let file = viewed_file(library, generated_path, expected_sha256, cancelled)?;
    let offset = byte_offset(&file.text, position, encoding, cancelled)?;
    source_in_file(library, file, offset, cancelled)
}

pub(super) fn byte_offset(
    text: &str,
    position: TextPosition,
    encoding: PositionEncoding,
    cancelled: &AtomicBool,
) -> Result<usize, LookupError> {
    check_cancelled(cancelled)?;
    let bytes = text.as_bytes();
    let mut cursor = 0;
    let mut line = 0;
    // File size was bounded by viewed_file; scanning uses no line-table allocation.
    while line < position.line {
        if cursor & 4095 == 0 {
            check_cancelled(cancelled)?;
        }
        let byte = *bytes.get(cursor).ok_or(LookupError::InvalidPosition)?;
        cursor += 1;
        if byte == b'\r' {
            if bytes.get(cursor) == Some(&b'\n') {
                cursor += 1;
            }
            line += 1;
        } else if byte == b'\n' {
            line += 1;
        }
    }
    let target = usize::try_from(position.character).map_err(|_| LookupError::InvalidPosition)?;
    let tail = text.get(cursor..).ok_or(LookupError::InvalidPosition)?;
    let mut units = 0usize;
    for (relative, ch) in tail.char_indices() {
        check_cancelled(cancelled)?;
        if units == target {
            return Ok(cursor + relative);
        }
        if matches!(ch, '\r' | '\n') {
            return Err(LookupError::InvalidPosition);
        }
        let width = match encoding {
            PositionEncoding::Utf8 => ch.len_utf8(),
            PositionEncoding::Utf16 => ch.len_utf16(),
            PositionEncoding::Utf32 => 1,
        };
        units = units
            .checked_add(width)
            .ok_or(LookupError::InvalidPosition)?;
        if units > target {
            return Err(LookupError::InvalidPosition);
        }
    }
    check_cancelled(cancelled)?;
    if units == target {
        Ok(text.len())
    } else {
        Err(LookupError::InvalidPosition)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn offset(
        text: &str,
        line: u32,
        character: u32,
        encoding: PositionEncoding,
    ) -> Result<usize, LookupError> {
        byte_offset(
            text,
            TextPosition { line, character },
            encoding,
            &AtomicBool::new(false),
        )
    }

    #[test]
    fn encoded_columns_preserve_unicode_boundaries() -> Result<(), LookupError> {
        let text = "aé🦀e\u{301}";
        for (encoding, columns) in [
            (PositionEncoding::Utf8, [0, 1, 3, 7, 8, 10]),
            (PositionEncoding::Utf16, [0, 1, 2, 4, 5, 6]),
            (PositionEncoding::Utf32, [0, 1, 2, 3, 4, 5]),
        ] {
            for (column, expected) in columns.into_iter().zip([0, 1, 3, 7, 8, 10]) {
                assert_eq!(offset(text, 0, column, encoding)?, expected);
            }
            assert_eq!(
                offset(text, 0, u32::MAX, encoding),
                Err(LookupError::InvalidPosition)
            );
        }
        for column in [2, 4, 5, 6, 9] {
            assert_eq!(
                offset(text, 0, column, PositionEncoding::Utf8),
                Err(LookupError::InvalidPosition)
            );
        }
        assert_eq!(
            offset(text, 0, 3, PositionEncoding::Utf16),
            Err(LookupError::InvalidPosition)
        );
        Ok(())
    }

    #[test]
    fn newline_sequences_and_eof_are_explicit() -> Result<(), LookupError> {
        for encoding in [
            PositionEncoding::Utf8,
            PositionEncoding::Utf16,
            PositionEncoding::Utf32,
        ] {
            for (line, column, expected) in [
                (0, 1, 1),
                (1, 0, 3),
                (2, 0, 4),
                (3, 0, 6),
                (3, 1, 7),
                (4, 0, 9),
            ] {
                assert_eq!(offset("a\r\n\nb\rc\r\n", line, column, encoding)?, expected);
            }
            for (line, column) in [(0, 2), (1, 1), (5, 0)] {
                assert_eq!(
                    offset("a\r\n\nb\rc\r\n", line, column, encoding),
                    Err(LookupError::InvalidPosition)
                );
            }
            assert_eq!(offset("", 0, 0, encoding)?, 0);
            assert_eq!(offset("x\n\r", 2, 0, encoding)?, 3);
            assert_eq!(
                offset("x", 1, 0, encoding),
                Err(LookupError::InvalidPosition)
            );
        }
        assert_eq!(
            byte_offset(
                "",
                TextPosition {
                    line: 0,
                    character: 0,
                },
                PositionEncoding::Utf16,
                &AtomicBool::new(true)
            ),
            Err(LookupError::Cancelled)
        );
        Ok(())
    }
}
