//! Whole-range navigation for diagnostic spans and editor selections.
use super::{
    LookupError, PositionEncoding, SourceLookup, TextPosition, check_cancelled, positions,
    source_for_span_in_file, viewed_file,
};
use crate::native::NativeLibrary;
use serde::Serialize;
use std::sync::atomic::AtomicBool;
use wow_reference::native::Span;

/// Half-open editor range with zero-based, explicitly encoded endpoints.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub struct TextRange {
    pub start: TextPosition,
    pub end: TextPosition,
}

/// Find the most precise mapping containing the entire generated byte range.
///
/// A member map wins only when it contains the whole nonempty selection. A
/// range crossing members can use their containing declaration, but independent
/// declarations are never stitched into a fabricated source range. Equal best
/// matches remain explicit. Unmapped means no single stored map contains the
/// full range, not that every selected byte is unmapped or the API is absent.
///
/// Zero-width ranges behave exactly as `source_at`, including EOF. Reversed,
/// out-of-file and mid-codepoint endpoints return `LookupError::InvalidPosition`.
/// The digest, profile, complete selected map set and source identities use the
/// same validation as point queries. No source offset is interpolated from the
/// generated text: candidates retain the actual stored source descriptors.
pub fn source_for_range<'a>(
    library: &'a NativeLibrary<'_>,
    generated_path: &str,
    expected_sha256: &str,
    range: Span,
    cancelled: &AtomicBool,
) -> Result<SourceLookup<'a>, LookupError> {
    let file = viewed_file(library, generated_path, expected_sha256, cancelled)?;
    source_for_span_in_file(library, file, range, cancelled)
}

/// Convert both encoded endpoints against the same digest-bound file, then
/// perform whole-range lookup. LF, CRLF, bare CR and Unicode handling are shared
/// with `source_at_position`; invalid columns reject without protocol clamping.
/// Returned source and generated locations remain half-open UTF-8 byte ranges.
pub fn source_for_text_range<'a>(
    library: &'a NativeLibrary<'_>,
    generated_path: &str,
    expected_sha256: &str,
    range: TextRange,
    encoding: PositionEncoding,
    cancelled: &AtomicBool,
) -> Result<SourceLookup<'a>, LookupError> {
    let file = viewed_file(library, generated_path, expected_sha256, cancelled)?;
    let selected = byte_span(&file.text, range, encoding, cancelled)?;
    source_for_span_in_file(library, file, selected, cancelled)
}

pub(super) fn byte_span(
    text: &str,
    range: TextRange,
    encoding: PositionEncoding,
    cancelled: &AtomicBool,
) -> Result<Span, LookupError> {
    check_cancelled(cancelled)?;
    if (range.start.line, range.start.character) > (range.end.line, range.end.character) {
        return Err(LookupError::InvalidPosition);
    }
    let start = positions::byte_offset(text, range.start, encoding, cancelled)?;
    let end = if range.start == range.end {
        start
    } else {
        positions::byte_offset(text, range.end, encoding, cancelled)?
    };
    check_cancelled(cancelled)?;
    Ok(Span { start, end })
}

pub(super) fn covers(mapping: Span, selected: Span) -> bool {
    mapping.start <= selected.start
        && selected.end <= mapping.end
        && (selected.start != selected.end || selected.start < mapping.end)
}
