//! Registry18 direct native source roles; earlier registries remain frozen.
use super::*;

pub(super) fn extend(
    entities: &mut Vec<GraphEntityKindDefinition>,
    relations: &mut Vec<GraphRelationKindDefinition>,
) -> ProjectResult<()> {
    for (kind, fields, confidence) in [
        (
            "source_project",
            vec![
                "project",
                "project_snapshot",
                "source_snapshot",
                "profile_digest",
                "content_manifest_digest",
                "admission_digest",
                "package_binding",
            ],
            GraphConfidence::Proven,
        ),
        (
            "source_toc_manifest",
            vec!["document", "plan_digest"],
            GraphConfidence::Derived,
        ),
        (
            "source_toc_variant",
            vec![
                "document",
                "flavor",
                "selected_root",
                "load_on_demand",
                "static_phase",
                "order_group",
                "reachability",
            ],
            GraphConfidence::Derived,
        ),
        (
            "source_toc_load_occurrence",
            vec![
                "fact_id",
                "document",
                "ordinal",
                "file_kind",
                "selection",
                "conditions_digest",
                "repeated",
                "bootstrap",
                "load_unit_witness",
                "static_phase",
                "order_group",
                "reachability",
            ],
            GraphConfidence::Derived,
        ),
        (
            "source_toc_load_policy",
            vec![
                "fact_id",
                "selection",
                "declared_state",
                "effective_state",
                "conflicting",
            ],
            GraphConfidence::Derived,
        ),
        (
            "xml_source_document",
            vec!["scope", "document", "document_digest", "content_digest"],
            GraphConfidence::Proven,
        ),
        (
            "xml_source_occurrence",
            vec![
                "scope",
                "document",
                "document_digest",
                "occurrence",
                "role",
                "source_handle",
            ],
            GraphConfidence::Proven,
        ),
        (
            "xml_source_script_site",
            vec![
                "scope",
                "document",
                "document_digest",
                "occurrence",
                "state",
            ],
            GraphConfidence::Proven,
        ),
        (
            "xml_source_load_site",
            vec![
                "scope",
                "document",
                "document_digest",
                "occurrence",
                "state",
            ],
            GraphConfidence::Proven,
        ),
        (
            "xml_source_parent_reference",
            vec![
                "scope",
                "document",
                "document_digest",
                "occurrence",
                "reference_id",
                "state",
            ],
            GraphConfidence::Proven,
        ),
    ] {
        entities.push(
            GraphEntityKindDefinition::new(
                kind,
                vec!["blizzard_ui_source".into()],
                fields.into_iter().map(Into::into).collect(),
                vec![confidence],
            )
            .map_err(|_| invalid())?,
        );
    }
    for (id, kind, sources, targets, confidences) in [
        (
            "source_project_contains_package",
            GraphRelationKind::Contains,
            vec!["source_project"],
            vec!["source_package"],
            vec![GraphConfidence::Proven],
        ),
        (
            "source_project_contains_file",
            GraphRelationKind::Contains,
            vec!["source_project"],
            vec!["source_file"],
            vec![GraphConfidence::Proven],
        ),
        (
            "source_project_contains_raw_member",
            GraphRelationKind::Contains,
            vec!["source_project"],
            vec![PLATFORM_RAW_MEMBER_KIND],
            vec![GraphConfidence::Proven],
        ),
        (
            "source_package_contains_raw_member",
            GraphRelationKind::Contains,
            vec!["source_package"],
            vec![PLATFORM_RAW_MEMBER_KIND],
            vec![GraphConfidence::Proven],
        ),
        (
            "source_package_selects_toc",
            GraphRelationKind::Defines,
            vec!["source_package"],
            vec!["source_toc_manifest"],
            vec![GraphConfidence::Derived],
        ),
        (
            "source_toc_defines_variant",
            GraphRelationKind::Defines,
            vec!["source_toc_manifest"],
            vec!["source_toc_variant"],
            vec![GraphConfidence::Derived],
        ),
        (
            "source_toc_contains_occurrence",
            GraphRelationKind::Contains,
            vec!["source_toc_variant"],
            vec!["source_toc_load_occurrence"],
            vec![GraphConfidence::Derived],
        ),
        (
            "source_toc_occurrence_loads",
            GraphRelationKind::Loads,
            vec!["source_toc_load_occurrence"],
            vec!["source_file"],
            vec![GraphConfidence::Derived, GraphConfidence::Possible],
        ),
        (
            "source_toc_occurs_before",
            GraphRelationKind::LoadsBefore,
            vec!["source_toc_load_occurrence"],
            vec!["source_toc_load_occurrence"],
            vec![GraphConfidence::Derived],
        ),
        (
            "source_toc_defines_load_policy",
            GraphRelationKind::Defines,
            vec!["source_toc_variant"],
            vec!["source_toc_load_policy"],
            vec![GraphConfidence::Derived],
        ),
        (
            "xml_file_contains_document",
            GraphRelationKind::Contains,
            vec!["source_file"],
            vec!["xml_source_document"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_document_contains_occurrence",
            GraphRelationKind::Contains,
            vec!["xml_source_document"],
            vec!["xml_source_occurrence"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_lexical_contains",
            GraphRelationKind::Contains,
            vec!["xml_source_occurrence"],
            vec!["xml_source_occurrence"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_occurrence_source_span",
            GraphRelationKind::Owns,
            vec!["xml_source_occurrence"],
            vec!["source_span"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_occurrence_owns_script_site",
            GraphRelationKind::Owns,
            vec!["xml_source_occurrence"],
            vec!["xml_source_script_site"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_occurrence_owns_load_site",
            GraphRelationKind::Owns,
            vec!["xml_source_occurrence"],
            vec!["xml_source_load_site"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_include_target",
            GraphRelationKind::Loads,
            vec!["xml_source_load_site"],
            vec!["source_file"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_external_script_target",
            GraphRelationKind::Loads,
            vec!["xml_source_load_site"],
            vec!["source_file"],
            vec![GraphConfidence::Proven],
        ),
        (
            "xml_occurrence_owns_parent_reference",
            GraphRelationKind::Owns,
            vec!["xml_source_occurrence"],
            vec!["xml_source_parent_reference"],
            vec![GraphConfidence::Proven],
        ),
    ] {
        relations.push(
            GraphRelationKindDefinition::new(
                id,
                kind,
                sources.into_iter().map(Into::into).collect(),
                targets.into_iter().map(Into::into).collect(),
                confidences,
            )
            .map_err(|_| invalid())?,
        );
    }
    Ok(())
}
